### PR TITLE
fix: help flag doesn't take an argument

### LINKED ISSUE #442: bug: help doesn't print for some commands
It seems like the `cli` library will accept an argument to the `--help` flag so the following command doesn't work properly... It should just print the help and ignore other flags and arguments.
```
$ go run ./internal/cmd/todos/ --help foo/
exit status 3
```

### PR DESCRIPTION
**Pull request by ianlewis**
Fixes #442

### CODE REVIEW

File: internal/cmd/todos/app.go [hunk 1]
```diff
@@ -58,6 +58,23 @@ var (
...
+// TODO(github.com/urfave/cli/issues/1809): Remove init func when upstream bug is fixed.
+//
+//nolint:gochecknoinits // init needed needed for global variable.
+func init() {
+	// Set the HelpFlag to a random name so that it isn't used. `cli` handles
+	// the flag with the root command such that it takes a command name argument
+	// but we don't use commands.
+	// This flag is hidden by the help output.
+	// See: #442
+	//
```
Comment (ianlewis) [inline internal/cmd/todos/app.go:70]:
```suggestion
```
